### PR TITLE
fix: os insensitive path handling

### PR DESCRIPTION
**Pull request by Meemaw**
## What kind of change does this PR introduce?

- Fixes https://github.com/toomuchdesign/next-page-tester/issues/31
- Adds CI (using Github Actions) to run on different platforms (ubuntu, windows, OSx) to prevent future regressions

## Does this PR introduce a breaking change?

No

## Please check if the PR fulfills these requirements:

- [x] Tests for the changes have been added
- [x] Docs have been added / updated

### CODE REVIEW

**Comment by Meemaw** [comment]
Passing checks/tests can be seen here: https://github.com/Meemaw/next-page-tester/pull/1

**Comment by toomuchdesign** [comment]
Looks great!
Shall we consider getting rid of Travis at all? The only thing the current GH actions are missing in sending test coverage report to Coveralls.

Travis has this `after_success` hook: `cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js`.

I saw there's an action for that:
https://github.com/marketplace/actions/coveralls-github-action

**Comment by Meemaw** [comment]
I would get rid of travis tbh, but would leave that for a separate PR.

**Comment by toomuchdesign** [comment]
Good to me, I found that since we're using matrix we are supposed to use this[ awkward `if` trick](https://github.com/codecov/codecov-action/issues/40#issuecomment-653903770):

```
steps:
  - name: Post Coverage
    uses: codecov/codecov-action@v1
    if: matrix.os == 'ubuntu-latest' && matrix.node-version == '10.x'
```

**Pull request merged**
