### PR TITLE
fix: client side SingletonRouter

### PR DESCRIPTION
**Pull request by Meemaw**
## What kind of change does this PR introduce?

Enables client side `SingletonRouter`  routing exported from `next/router`.

Fixes https://github.com/toomuchdesign/next-page-tester/issues/160

## What is the current behaviour?

It is not possible to use client side `SingletonRouter`  routing exported from `next/router`.

## Does this PR introduce a breaking change?

No

## Please check if the PR fulfills these requirements:

- [x] Tests for the changes have been added
- [ ] Docs have been added / updated

### CODE REVIEW

**Comment by Meemaw** [comment]
This is a super draft implementation that demonstrated one possible way to do it. As we have to "re-wire" a locally scoped variable in a module I don't see a better way than to somehow "hack" ourselves into the initialisation.

Open question:
- Where should we call this logic? Is the current place okay?
- How to handle non-jest environments? Do we even have to worry about them? I'm a bit sceptical its possible to run the library in other test runners anyway.

**Comment by toomuchdesign** [comment]
I know it might sound a bit punk but... how about not providing support `SingletonRouter`?  Is there anything `SingletonRouter` can do which `useRouter` can't?

**Comment by Meemaw** [comment]
> I know it might sound a bit punk but... how about not providing support `SingletonRouter`? Is there anything `SingletonRouter` can do which `useRouter` can't?

No, but it means that projects that are using it have no change to use `next-page-tester`. I'm not saying its good usage (I'm against it personally) and it doesn't feel React'ish.

In a project I'm currently trying to integrate `next-page-tester` we use it all over the place and it would be impossible to get rid of it ATM 😢

**Comment by toomuchdesign** [comment]
Hi @Meemaw,
sorry for keeping you waiting, I'haven't had much time to spend in extra screen activity lately.

If I get it right, here we're patching the default `next/router` entry point with an object created in `src/router/makeRouterMock.ts` by `makeRouterMock` function.

Since `makeRouterMock` replaces the mock instance (`SingletonRouter`) at every run, is the newly created mock always available through `next/router` default entry point? Or the mock is then one available at `jest.mock` time?

### Alternative 1
This PR seems quite all about Jest configuration. Shall we consider providing the minimum necessary API to let users mock `next/router` on their side?

### Alternative 2
Would it be much of a hassle wrapping the pages consuming `SingletonRouter` with a HOC providing the hook version of Next.js router?

**Comment by Meemaw** [comment]
> ### Alternative 1
> This PR seems quite all about Jest configuration. Shall we consider providing the minimum necessary API to let users mock `next/router` on their side?
> 

I was thinking about that -- and tried it but... I couldn't get it to wrong. Actually any change to the current approach breaks it 😢 

> ### Alternative 2
> Would it be much of a hassle wrapping the pages consuming `SingletonRouter` with a HOC providing the hook version of Next.js router?

1. Yes, not really possible as the `SingletonRouter` is used across router helper utility functions that are spread all over the place ... 
2. I mentioned this in one of the PRs some time ago: we shouldn't require users to change their code in order to adopt/use to library. They will more likely just give up and not use it.

**Comment by toomuchdesign** [comment]
Another punk idea. What if we tried to misuse `router` option to notify `jest` (or any other test runner) that `next/router` mock should be updated? After all we call it every time `SingletonRouter` should be updated.

**Comment by Meemaw** [comment]
> Another punk idea. What if we tried to misuse `router` option to notify `jest` (or any other test runner) that `next/router` mock should be updated? After all we call it every time `SingletonRouter` should be updated.

Not sure what you mean by this 🤔

**Comment by toomuchdesign** [comment]
I'll try to put down something :)

**Comment by toomuchdesign** [comment]
Howdy @Meemaw?
I set up a demo branch to mock singletonRouter in user land by misusing `router` option:
https://github.com/toomuchdesign/next-page-tester/tree/fix-client-singleton-router-II

I'm sure it's improvable and I'd be happy if you validate it and take care of it. If you found it decent enough, we might merge new tests and provide this setup as docs in our `/example` folder.

PS. I'd like to keep commit `638f6bc`, since it helped me a lot understanding what tests were doing :)

Let me know! 👊

**Comment by Meemaw** [comment]
Hey @toomuchdesign 

That looks promising 🎉 

Do you need to override each of the properties on `SingletonRouter` manually? If `SingletonRouter = router` doesn't work I think we can do this:


```javascript
Object.assign(SingletonRouter, router);
```

**Comment by toomuchdesign** [comment]
I'd like to be wrong, but I'd say yes, you need to mutate `SingletonRouter` object.

**Comment by toomuchdesign** [comment]
I remember `Object.assign(SingletonRouter, router)` causing issues with the way `SingletonRouter` is generated (some getter fun involved).

**Comment by Meemaw** [comment]
> I remember `Object.assign(SingletonRouter, router)` causing issues with the way `SingletonRouter` is generated (some getter fun involved).

Managed to get it to work in https://github.com/toomuchdesign/next-page-tester/pull/173

**Pull request closed without merging**
