### PR TITLE
refactor: fine tune things for Jest v27

### PR DESCRIPTION
**Pull request by toomuchdesign**
## What kind of change does this PR introduce?

Bug fix

## What is the current behaviour?

`next-page-tester` doesn't work with jest 27

## What is the new behaviour?

Update dependencies to use Jest v27 and update `next-page-tester` to work with it.

## Does this PR introduce a breaking change?

TBD

## Please check if the PR fulfills these requirements:

- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated

### CODE REVIEW

**Comment by toomuchdesign** [comment]
Current status: `setImmediate` errors are gone. Now we have:

```
 Hooks cannot be defined inside tests. Hook of type "afterEach" is nested within "{test-assertion}".
```

**Comment by Meemaw** [comment]
Not sure if related: https://github.com/facebook/jest/issues/11471

If we fail to find cause for this, we could ask SimenB for help.

**Comment by toomuchdesign** [comment]
Hopefully the issue you mentioned is what we struggled with when we had to import all the components necessary for rendering in a single go :) Let's take some time to dig into `jest-circus`

**Comment by toomuchdesign** [comment]
The error message come from `jest-circus` [here](https://github.com/facebook/jest/blob/bc50e7f360ab1845abbaa0b3ad788caead0d3174/packages/jest-circus/src/eventHandler.ts#L103). I guess the mentioned hooks are not React hooks but Jest's `afterEach` hooks :)

**Comment by Meemaw** [comment]
Yep, if you comment our the `afterEach` in `testHelpers.ts` you wont see those errors anymore (but bunch of others).

That gets re-executed multiple times because of `jest.isolateModules`. I guess we need to figure a way to only init that hook once?

**Comment by toomuchdesign** [comment]
The error call stack seems to point us to the `@testing-library/react` import in  [`src/__tests__/__utils__/renderWithinNextRoot.ts`](https://github.com/toomuchdesign/next-page-tester/blob/master/src/__tests__/__utils__/renderWithinNextRoot.ts#L1)

```
    Hooks cannot be defined inside tests. Hook of type "afterEach" is nested within "does not render custom App nor receives props from it".

    > 1 | import { render } from '@testing-library/react';
        | ^
      2 | import { NEXT_ROOT_ELEMENT_ID } from '../../constants';
      3 |
      4 | function makeNextRootElement(): Element {

      at eventHandler (node_modules/jest-circus/build/eventHandler.js:107:11)
      at Object.<anonymous> (node_modules/@testing-library/react/dist/index.js:32:5)
      at Object.<anonymous> (src/__tests__/__utils__/renderWithinNextRoot.ts:1:1)
      at Object.<anonymous> (src/__tests__/__utils__/index.ts:11:1)
      at Object.<anonymous> (src/__tests__/use-app/__fixtures__/custom-app-with-gip/pages/page.js:2:1)
      at Object.loadFile (src/loadFile.ts:6:10)
      at loadPageFiles (src/getNextFiles.ts:26:15)
      at src/getNextFiles.ts:43:15
      at src/utils.ts:139:16
      at Object.executeWithFreshModules (src/utils.ts:138:10)
      at src/getNextFiles.ts:42:7
      at Object.executeAsIfOnServerSync (src/server.ts:36:12)
      at Object.loadExistingPageFiles (src/getNextFiles.ts:41:13)
      at Object.getPageObject (src/getPageObject/getPageObject.ts:18:19)
      at Object.getPageInfo (src/page/getPageInfo.ts:16:22)
      at Object.getPage (src/getPage.tsx:102:36)
      at Object.<anonymous> (src/__tests__/use-app/use-app.test.tsx:171:26)
```

**Comment by toomuchdesign** [comment]
I don't know why, but the `afterEach` hook triggering the error seems to be `react-testing-library`'s cleanup.

When I disable it with:
```
 process.env.RTL_SKIP_AUTO_CLEANUP = 'true';
 ```
...the error goes away.

**Comment by Meemaw** [comment]
> I don't know why, but the `afterEach` hook triggering the error seems to be `react-testing-library`'s cleanup.
> 
> When I disable it with:
> 
> ```
>  process.env.RTL_SKIP_AUTO_CLEANUP = 'true';
> ```
> 
> ...the error goes away.

Do the test pass if we disable that? I think we can disable that as we are doing our own cleanup anyhow?

**Comment by toomuchdesign** [comment]
We have an issue with `tiny-glob` on windows now. Trying to figure out where the problem lies.

**Comment by toomuchdesign** [comment]
I restored `fast-glob` + `setImmediate` polyfill. We had still the CI failing and it seems that by disabling `aws-amplify` tests the situation got back under control.

**Review by Meemaw — APPROVED** [review]
This LGTM apart from the disabled test. Any ideas what broke?

**Comment by toomuchdesign** [comment]
Not sure what happened with that test. Here is the [log](https://github.com/toomuchdesign/next-page-tester/pull/223/checks?check_run_id=2726525437#step:4:84) and the failing lines:

```
[BABEL] Note: The code generator has deoptimised the styling of /home/runner/work/next-page-tester/next-page-tester/node_modules/@aws-sdk/client-pinpoint/dist/cjs/protocols/Aws_restJson1.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /home/runner/work/next-page-tester/next-page-tester/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js as it exceeds the max of 500KB.
Killed
npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! next-page-tester@0.25.0 test:source: `npm run test:format && npm run test:ts && npm t -- --coverage`
npm ERR! Exit status 1
```

**Pull request merged**
