### PR TITLE
fix: await `loadConfig`

### PR DESCRIPTION
**Pull request by geritol**
fixes https://github.com/toomuchdesign/next-page-tester/issues/185

## What kind of change does this PR introduce?

Bug fix, feature, docs update, ...

## What is the current behaviour?

You can also link to an open issue here.

## What is the new behaviour?

...

## Does this PR introduce a breaking change?

What changes might users need to make in their application due to this PR?

## Please check if the PR fulfills these requirements:

- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated

### CODE REVIEW

**Review by toomuchdesign — APPROVED** [review]
Hi @geritol, thanks for the issue and PR :)

**Comment by geritol** [comment]
@toomuchdesign Thanks for merging!
Do you plan to do a release of this soon, or should I install the plugin from my repo for now?

**Comment by toomuchdesign** [comment]
We'll try to release as soon as we get usual maintenance chores done. Maybe this afternoon.

**Comment by toomuchdesign** [comment]
I spoke too soon :) We have red CI #187

**Comment by toomuchdesign** [comment]
v0.23.0 is available 🚀

**Pull request merged**
