### PR TITLE
test: suite for expected global object behaviour

### PR DESCRIPTION
**Pull request by Meemaw**
## What kind of change does this PR introduce?

Bug fix, feature, docs update, ...

## What is the current behaviour?

You can also link to an open issue here.

## What is the new behaviour?

...

## Does this PR introduce a breaking change?

What changes might users need to make in their application due to this PR?

## Please check if the PR fulfills these requirements:

- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated

### CODE REVIEW

**Comment by Meemaw** [comment]
@toomuchdesign added some more tests for the problematic behaviour regarding module imports (see https://github.com/toomuchdesign/next-page-tester/issues/64). I think if we are somehow able to make these tests pass, it will solve all problems.

**Comment by toomuchdesign** [comment]
`jest.isolateModules` has a few open issues. Linking here just for documentation purpose:

- [jest.isolateModules not accepting async functions](https://github.com/facebook/jest/issues/10428)
- [does not work if module has already been required with a non-isolated method](https://github.com/facebook/jest/issues/7863)

**Comment by toomuchdesign** [comment]
Brief report after a few attempts of working around ES/`jest` modules and global objects.

`jest.isolateModules` seems quite a powerful pattern but it currently comes with a couple of unexpected limitations.

### jest.isolateModules relativity

I confirm that [this issue](https://github.com/facebook/jest/issues/7863) still occurs and `jest.isolateModules` doesn't load a fresh module if that modules is already imported outside a `jest.isolateModules` call.

This means that, in order to ensure we get modules isolation, we should wrap all tests in a `jest.isolateModules` call :)

### jest.isolateModules + Typescript

Since we have to use `require` from inside `jest.isolateModules`, I found out that Typescript looses typing information of those modules imported with `require`. Maybe I'm missing a TS config or something else? Eg:

```js
jest.isolateModules(() => {
  const { createElement } = require('react');
  // createElement: any
});
```

### React multiple instances error

Taking the opposite approach with `jest.resetModules()` took me to the error where React detects hook calls to different React instances.

```
Error: Uncaught [Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
```

**Comment by Meemaw** [comment]
Didnt dive into the problem yet, but there might be some ideas in this issue: https://github.com/facebook/jest/issues/8987

**Comment by toomuchdesign** [comment]
Well, it seems we're going to have `jest.isolateModules` fixed: https://github.com/facebook/jest/pull/10963 😄

**Pull request closed without merging**
