### PR TITLE
feat: Add custom wrapper for _app

### LINKED ISSUE #210: Custom wrapper for _app
## 🚀 Feature Proposal

It would be great to have a way to customize _app. In source code I've seen that there is already a wrapper for `Page` and it have types for custom app.

## Motivation

In my project we use `next-translate` (via webpack plugin) and keep some layout  (header, footer) `in _app.tsx`. AFAIK I can't use webpack plugin to load locales during testing with `next-page-tester`, so I need to wrap app in provider and load them manually. I tried to wrap `Page` by using `wrapper.Page` but then my header and footer are left without locales.

I can try to implement this and submit a PR but I definitely would need help with it. I've already tried to modify this package but with no luck.

## Example

Something like this:
```typescript
const { render } = await getPage({
    route: "/",
    useDocument: true,
    wrapper: {
        App: App => {
             return appWithI18N(App);
        },
    },
});
```
or like this:
```typescript
const { render } = await getPage({
    route: "/",
    useDocument: true,
    wrapper: {
        App: App => {
             App.getInitialProps = async () => ({
                pageProps: {
                    ...(await loadNamespaces()),
                }
             });

             return App;
        },
    },
});
```

### PR DESCRIPTION
**Pull request by evocateur**
Closes #210

## What kind of change does this PR introduce?

Adds a `wrapper.App` option, similar to the existing `wrapper.Page`.

## What is the current behaviour?

Only a `Page` wrapper is available, which is certainly useful, but insufficient for certain behaviors.

## What is the new behaviour?

#210

## Does this PR introduce a breaking change?

No

## Please check if the PR fulfills these requirements:

- [x] Tests for the changes have been added
- [x] Docs have been added / updated

### CODE REVIEW

**Comment by toomuchdesign** [comment]
Hi @evocateur,
thanks for the PR! 🙌 

The CI seems to be failing because of a formatting issue. Would you mind running `npm run prettier:fix` and commit again the result?

Cheers!

**Comment by evocateur** [comment]
@toomuchdesign Thanks, sorry about that! Trying to do too many things at once, forgot a fundamental step 😅

**Review by Meemaw — APPROVED** [review]
LGTM

**Review by toomuchdesign — APPROVED** [review]
Looks good to me! Thanks @evocateur! I'll leave it here for a little while to let anybody interested to check out 👍

**Comment by toomuchdesign** [comment]
@all-contributors please add @evocateur for code

**Pull request merged**
